// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_s8qDok7aapAyLborzDEX9pmA7OG4GnE',
    appId: '1:631494873953:web:2ef1fcc478816fc6e2ab20',
    messagingSenderId: '631494873953',
    projectId: 'flutter-e-commerce-app-7b592',
    authDomain: 'flutter-e-commerce-app-7b592.firebaseapp.com',
    storageBucket: 'flutter-e-commerce-app-7b592.firebasestorage.app',
    measurementId: 'G-TR76ZC64Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeg5ZMdxMpaGtD-fnXym6wKWXMAyJeVNM',
    appId: '1:631494873953:android:677598bd67a9886be2ab20',
    messagingSenderId: '631494873953',
    projectId: 'flutter-e-commerce-app-7b592',
    storageBucket: 'flutter-e-commerce-app-7b592.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT96A23ahjCGiVkZXsAIdvYaafuY7xLO4',
    appId: '1:631494873953:ios:659ff6e528ab4f97e2ab20',
    messagingSenderId: '631494873953',
    projectId: 'flutter-e-commerce-app-7b592',
    storageBucket: 'flutter-e-commerce-app-7b592.firebasestorage.app',
    iosBundleId: 'com.example.flutterECommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT96A23ahjCGiVkZXsAIdvYaafuY7xLO4',
    appId: '1:631494873953:ios:659ff6e528ab4f97e2ab20',
    messagingSenderId: '631494873953',
    projectId: 'flutter-e-commerce-app-7b592',
    storageBucket: 'flutter-e-commerce-app-7b592.firebasestorage.app',
    iosBundleId: 'com.example.flutterECommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_s8qDok7aapAyLborzDEX9pmA7OG4GnE',
    appId: '1:631494873953:web:46cae53726e17bb6e2ab20',
    messagingSenderId: '631494873953',
    projectId: 'flutter-e-commerce-app-7b592',
    authDomain: 'flutter-e-commerce-app-7b592.firebaseapp.com',
    storageBucket: 'flutter-e-commerce-app-7b592.firebasestorage.app',
    measurementId: 'G-K0SM90C175',
  );
}
